//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.0
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyProduct("NHibernate.ProxyGenerators")]
[assembly: AssemblyCompany("NHibernate.info")]
[assembly: AssemblyCopyright("Copyright © NHibernate Community 2011 - 2015")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyVersion("2.1.0.917")]
[assembly: AssemblyFileVersion("2.1.0.917")]


